"""initial_schema

Revision ID: 6ee9e6787acd
Revises: 
Create Date: 2026-07-04 15:46:30.796202
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6ee9e6787acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Purge stale data from all tables (leftover from old project)
    op.execute('TRUNCATE TABLE transcript_messages, findings, risk_scores, conversations, reports, integrations, audit_logs, stress_test_runs, personas, agents, users CASCADE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_personas',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['stress_test_runs.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'persona_id')
    )
    op.drop_table('Alert')
    op.drop_table('WorkflowRun')
    op.drop_table('Investigation')
    op.drop_index('Merchant_email_key', table_name='Merchant')
    op.drop_table('Merchant')
    op.add_column('agents', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.alter_column('agents', 'model_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_agents_id', table_name='agents')
    op.drop_column('agents', 'deleted_at')
    op.add_column('audit_logs', sa.Column('details_json', sa.Text(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'updated_at')
    op.add_column('conversations', sa.Column('stress_test_run_id', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_index('ix_conversations_persona_id', table_name='conversations')
    op.drop_index('ix_conversations_run_id', table_name='conversations')
    op.create_index(op.f('ix_conversations_stress_test_run_id'), 'conversations', ['stress_test_run_id'], unique=False)
    op.drop_constraint('conversations_run_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'stress_test_runs', ['stress_test_run_id'], ['id'])
    op.drop_column('conversations', 'summary')
    op.drop_column('conversations', 'run_id')
    op.drop_column('conversations', 'updated_at')
    op.add_column('findings', sa.Column('stress_test_run_id', sa.Integer(), nullable=False))
    op.add_column('findings', sa.Column('finding_type', sa.String(length=100), nullable=False))
    op.add_column('findings', sa.Column('details_json', sa.Text(), nullable=True))
    op.alter_column('findings', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_findings_category', table_name='findings')
    op.drop_index('ix_findings_conversation_id', table_name='findings')
    op.drop_index('ix_findings_id', table_name='findings')
    op.drop_index('ix_findings_run_id', table_name='findings')
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_stress_test_run_id'), 'findings', ['stress_test_run_id'], unique=False)
    op.drop_constraint('findings_run_id_fkey', 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'stress_test_runs', ['stress_test_run_id'], ['id'])
    op.drop_column('findings', 'metadata')
    op.drop_column('findings', 'category')
    op.drop_column('findings', 'expected_behavior')
    op.drop_column('findings', 'agent_response')
    op.drop_column('findings', 'run_id')
    op.drop_column('findings', 'updated_at')
    op.add_column('integrations', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('integrations', sa.Column('integration_type', sa.String(length=50), nullable=False))
    op.add_column('integrations', sa.Column('config_json', sa.Text(), nullable=True))
    op.drop_index('ix_integrations_id', table_name='integrations')
    op.drop_column('integrations', 'config')
    op.drop_column('integrations', 'provider')
    op.drop_column('integrations', 'display_name')
    op.add_column('personas', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('personas', 'persona_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('personas', 'attack_style',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_personas_id', table_name='personas')
    op.drop_column('personas', 'deleted_at')
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('stress_test_run_id', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('status', sa.String(length=50), server_default='generating', nullable=False))
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_reports_id', table_name='reports')
    op.drop_index('ix_reports_run_id', table_name='reports')
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_constraint('reports_run_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'stress_test_runs', ['stress_test_run_id'], ['id'])
    op.drop_column('reports', 'overall_score')
    op.drop_column('reports', 'risk_level')
    op.drop_column('reports', 'findings_summary')
    op.drop_column('reports', 'run_id')
    op.drop_column('reports', 'recommendations')
    op.add_column('risk_scores', sa.Column('stress_test_run_id', sa.Integer(), nullable=False))
    op.add_column('risk_scores', sa.Column('details_json', sa.Text(), nullable=True))
    op.drop_index('ix_risk_scores_id', table_name='risk_scores')
    op.drop_index('ix_risk_scores_run_id', table_name='risk_scores')
    op.create_index(op.f('ix_risk_scores_stress_test_run_id'), 'risk_scores', ['stress_test_run_id'], unique=False)
    op.drop_constraint('risk_scores_run_id_fkey', 'risk_scores', type_='foreignkey')
    op.create_foreign_key(None, 'risk_scores', 'stress_test_runs', ['stress_test_run_id'], ['id'])
    op.drop_column('risk_scores', 'details')
    op.drop_column('risk_scores', 'run_id')
    op.drop_column('risk_scores', 'updated_at')
    op.drop_column('risk_scores', 'weight')
    op.add_column('stress_test_runs', sa.Column('config_json', sa.Text(), nullable=True))
    op.add_column('stress_test_runs', sa.Column('total_messages', sa.Integer(), server_default='0', nullable=False))
    op.add_column('stress_test_runs', sa.Column('findings_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('stress_test_runs', sa.Column('overall_score', sa.Float(), nullable=True))
    op.alter_column('stress_test_runs', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ix_stress_test_runs_agent_id', table_name='stress_test_runs')
    op.drop_index('ix_stress_test_runs_id', table_name='stress_test_runs')
    op.drop_column('stress_test_runs', 'error_message')
    op.drop_column('stress_test_runs', 'config')
    op.add_column('transcript_messages', sa.Column('message_index', sa.Integer(), nullable=False))
    op.add_column('transcript_messages', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.drop_index('ix_transcript_messages_id', table_name='transcript_messages')
    op.drop_column('transcript_messages', 'token_count')
    op.drop_column('transcript_messages', 'latency_ms')
    op.drop_column('transcript_messages', 'turn_number')
    op.drop_column('transcript_messages', 'updated_at')
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='user', nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'role')
    op.add_column('transcript_messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('transcript_messages', sa.Column('turn_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transcript_messages', sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('transcript_messages', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_transcript_messages_id', 'transcript_messages', ['id'], unique=False)
    op.drop_column('transcript_messages', 'metadata_json')
    op.drop_column('transcript_messages', 'message_index')
    op.add_column('stress_test_runs', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stress_test_runs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_stress_test_runs_id', 'stress_test_runs', ['id'], unique=False)
    op.create_index('ix_stress_test_runs_agent_id', 'stress_test_runs', ['agent_id'], unique=False)
    op.alter_column('stress_test_runs', 'progress',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('stress_test_runs', 'overall_score')
    op.drop_column('stress_test_runs', 'findings_count')
    op.drop_column('stress_test_runs', 'total_messages')
    op.drop_column('stress_test_runs', 'config_json')
    op.add_column('risk_scores', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_scores', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('risk_scores', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('risk_scores', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'risk_scores', type_='foreignkey')
    op.create_foreign_key('risk_scores_run_id_fkey', 'risk_scores', 'stress_test_runs', ['run_id'], ['id'])
    op.drop_index(op.f('ix_risk_scores_stress_test_run_id'), table_name='risk_scores')
    op.create_index('ix_risk_scores_run_id', 'risk_scores', ['run_id'], unique=False)
    op.create_index('ix_risk_scores_id', 'risk_scores', ['id'], unique=False)
    op.drop_column('risk_scores', 'details_json')
    op.drop_column('risk_scores', 'stress_test_run_id')
    op.add_column('reports', sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('findings_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_run_id_fkey', 'reports', 'stress_test_runs', ['run_id'], ['id'])
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.create_index('ix_reports_run_id', 'reports', ['run_id'], unique=False)
    op.create_index('ix_reports_id', 'reports', ['id'], unique=False)
    op.alter_column('reports', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'stress_test_run_id')
    op.drop_column('reports', 'user_id')
    op.add_column('personas', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_personas_id', 'personas', ['id'], unique=False)
    op.alter_column('personas', 'attack_style',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('personas', 'persona_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('personas', 'is_active')
    op.add_column('integrations', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('integrations', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_integrations_id', 'integrations', ['id'], unique=False)
    op.drop_column('integrations', 'config_json')
    op.drop_column('integrations', 'integration_type')
    op.drop_column('integrations', 'name')
    op.add_column('findings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('agent_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('expected_behavior', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key('findings_run_id_fkey', 'findings', 'stress_test_runs', ['run_id'], ['id'])
    op.drop_index(op.f('ix_findings_stress_test_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.create_index('ix_findings_run_id', 'findings', ['run_id'], unique=False)
    op.create_index('ix_findings_id', 'findings', ['id'], unique=False)
    op.create_index('ix_findings_conversation_id', 'findings', ['conversation_id'], unique=False)
    op.create_index('ix_findings_category', 'findings', ['category'], unique=False)
    op.alter_column('findings', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('findings', 'details_json')
    op.drop_column('findings', 'finding_type')
    op.drop_column('findings', 'stress_test_run_id')
    op.add_column('conversations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_run_id_fkey', 'conversations', 'stress_test_runs', ['run_id'], ['id'])
    op.drop_index(op.f('ix_conversations_stress_test_run_id'), table_name='conversations')
    op.create_index('ix_conversations_run_id', 'conversations', ['run_id'], unique=False)
    op.create_index('ix_conversations_persona_id', 'conversations', ['persona_id'], unique=False)
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    op.drop_column('conversations', 'completed_at')
    op.drop_column('conversations', 'started_at')
    op.drop_column('conversations', 'stress_test_run_id')
    op.add_column('audit_logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('audit_logs', 'details_json')
    op.add_column('agents', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_agents_id', 'agents', ['id'], unique=False)
    op.alter_column('agents', 'model_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('agents', 'metadata_json')
    op.create_table('Alert',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('merchantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('riskScore', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('riskLevel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('investigationId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['merchantId'], ['Merchant.id'], name='Alert_merchantId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='Alert_pkey')
    )
    op.create_table('WorkflowRun',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('merchantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('workflowType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'running'::text"), autoincrement=False, nullable=False),
    sa.Column('renderRunId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['merchantId'], ['Merchant.id'], name='WorkflowRun_merchantId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='WorkflowRun_pkey')
    )
    op.create_table('Merchant',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('deviceFingerprint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bankAccountNumber', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bankAccountIfsc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('riskScore', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('riskLevel', sa.TEXT(), server_default=sa.text("'low'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Merchant_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('Merchant_email_key', 'Merchant', ['email'], unique=True)
    op.create_table('Investigation',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('merchantId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('riskScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('riskMemo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['merchantId'], ['Merchant.id'], name='Investigation_merchantId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='Investigation_pkey')
    )
    op.drop_table('run_personas')
    # ### end Alembic commands ###
